version: "3.8"

services:
  posts-db:
    image: postgres
    container_name: posts-db
    environment:
      - POSTGRES_DB=postsDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=9009001537
    networks:
      - connektify-network
    volumes:
      - posts-db-data:/var/lib/postgresql/data

  user-db:
    image: postgres
    container_name: user-db
    environment:
      - POSTGRES_DB=userDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=9009001537
    networks:
      - connektify-network
    volumes:
      - user-db-data:/var/lib/postgresql/data

  posts-service:
    image: abhishek603/connektify/posts-service
    container_name: posts-service
    networks:
      - connektify-network
    depends_on:
      - posts-db

  user-service:
    image: abhishek603/connektify/user-service
    container_name: user-service
    networks:
      - connektify-network
    depends_on:
      - user-db

networks:
  connektify-network:

volumes:
  posts-db-data:
  user-db-data:
